[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"

[compat]
ColorTypes = "0.12"
CxxWrap = "0.17"
Observables = "0.5"
QML = "0.11"
julia = "1.10"
