[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
Qt6Graphs_jll = "7aac1016-a7e0-562a-8747-d0456fd6285f"
jlqml_jll = "6b5019fb-a83d-5b4e-a9f7-678a36c28df7"

[compat]
CxxWrap = "0.17"
QML = "0.12"
julia = "1.6"