[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
QMLMakie = "08f9cac3-3b11-4f1c-9d88-d0e81c500f64"

[compat]
CxxWrap = "0.17"
FileIO = "1.17"
Makie = "0.24"
Observables = "0.5"
QML = "0.12"
julia = "1.10"
